spring:
  application:
    name: imani
  datasource:
    url: jdbc:h2:mem:app
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
server:
  port: 8080
  address: 0.0.0.0
